variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    REPOSITORY_HOST: "gitlab.shopware.com:5005"
    PLATFORM_BRANCH: "6.2"
    IMAGE_NAME: "${REPOSITORY_HOST}/shopware-cloud/connect/php-static-analysis"

stages:
    - Build
    - Static analysis
    - Unit
    - E2E

cache:
    key: "Eternal static key"
    paths:
        - .composer
        - .npm

.sw6_base:
    image: shopware/development:latest
    before_script:
        - zip -rq plugin.zip .
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git --branch $PLATFORM_BRANCH
        - rm -rf development/platform
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform --branch $PLATFORM_BRANCH
        - unzip -q plugin.zip -d development/custom/plugins/SaasConnect
        - cd development
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

.sw6_base_services:
    services:
        -   name: mysql:5.7
            alias: mysql
        -   name: elastic/elasticsearch:7.1.1
            alias: elasticsearch
            command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]

Build-Analysis-Container:
    stage: Build
    only:
        refs:
            - merge_requests
            - master
        changes:
            - dev-ops/tools/*
            - dev-ops/tools/**/*
    image: docker
    services:
        -   name: docker:18.09.7-dind
            alias: docker
    script:
        - apk add git bash
        - docker login "${REPOSITORY_HOST}" -u $REGISTRY_USERNAME --password-stdin < $REGISTRY_PASSWORD_FILE
        - docker build dev-ops/tools -t "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker tag "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_NAME}:latest"
        - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker push "${IMAGE_NAME}:latest"

EasyCodingStandard:
    stage: Static analysis
    only:
        refs:
            - merge_requests
            - master
    image: "${IMAGE_NAME}:latest"
    script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - ecs check .


Psalm:
    stage: Static analysis
    extends:
        - .sw6_base
    only:
        refs:
            - merge_requests
            - master
    script:
        - cd custom/plugins/SaasConnect
        - make psalm


Phpstan:
    stage: Static analysis
    only:
        refs:
            - merge_requests
            - master
    extends:
        - .sw6_base
    script:
        - cd custom/plugins/SaasConnect
        - make phpstan

PhpInsights:
    stage: Static analysis
    only:
        refs:
            - merge_requests
            - master
    image: "${IMAGE_NAME}:latest"
    script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - phpinsights --no-interaction --min-quality=100 --min-complexity=75 --min-architecture=100 --min-style=100

Eslint Administration:
    stage: Static analysis
    only:
        refs:
            - merge_requests
            - master
    extends:
        - .sw6_base
    script:
        - cd custom/plugins/SaasConnect/src/Resources/app/administration
        - npm install
        - npm run eslint-junit > eslint-administration.junit.xml
    artifacts:
        reports:
            junit: development/custom/plugins/SaasConnect/src/Resources/app/administration/eslint-administration.junit.xml

Unit:
    stage: Unit
    only:
        refs:
            - merge_requests
            - master
    extends:
        - .sw6_base
        - .sw6_base_services
    script:
        - ./psh.phar init
        - ./psh.phar storefront:install-dependencies
        - ./psh.phar storefront:build
        - composer install -d custom/plugins/SaasConnect
        - composer dump-autoload -d custom/plugins/SaasConnect
        - php bin/console plugin:install --activate SaasConnect
        - ./psh.phar init-test-databases
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SaasConnect/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text

    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/
        reports:
            junit: development/build/artifacts/phpunit.junit.xml

Jest (Administration):
    stage: Unit
    only:
        refs:
            - merge_requests
            - master
    extends:
        - .sw6_base
        - .sw6_base_services
    script:
        - composer install
        - ./psh.phar administration:install-dependencies
        - npm --prefix custom/plugins/SaasConnect/src/Resources/app/administration/ install
        - PROJECT_ROOT=${CI_PROJECT_DIR}/development npm --prefix custom/plugins/SaasConnect/src/Resources/app/administration/ run unit

    coverage: '/^\s?All files[^|]*\|[^|]*\s+([\d\.]+)/'
    artifacts:
        paths:
            - development/build/artifacts/clover.xml
        reports:
            junit: development/build/artifacts/administration.junit.xml

Connect E2E:
    stage: E2E
    dependencies: []
    only:
        refs:
            - merge_requests
            - master
    extends:
        - .sw6_base
        - .sw6_base_services
    services:
        - name: docker:18.09.7-dind
          alias: docker
        - name: mysql:5.7
          alias: mysql

    script:
        - ./psh.phar init --APP_ENV="prod"
        - php bin/console plugin:install --activate -c SaasConnect
        - ./psh.phar administration:init --APP_ENV="prod"
        - ./psh.phar storefront:init --APP_ENV="prod"
        - ./psh.phar init-test-databases --APP_ENV="prod"
        - ./psh.phar e2e:dump-db
        - cp -v custom/plugins/SaasConnect/dev-ops/gitlab/cypress.env.json custom/plugins/SaasConnect/src/Resources/app/e2e/cypress.env.json
        - chown -R 1000:1000 .
        - npm --prefix custom/plugins/SaasConnect/src/Resources/app/e2e install --production
        - forever start -c "npm run start-e2e-proxy" --workingDir custom/plugins/SaasConnect/src/Resources/app/e2e/ ./custom/plugins/SaasConnect/src/Resources/app/e2e/
        - forever list
        - docker run --name cypress --add-host="docker.vm:$(hostname -I)" -v $(pwd)/custom/plugins/SaasConnect/src/Resources/app/e2e:/e2e -v $(pwd)/build:/build -w /e2e cypress/included:4.4.0
        - docker rm -f cypress
    artifacts:
        when: always
        paths:
            - development/build/artifacts/e2e/
        reports:
            junit: development/build/artifacts/e2e/*.xml
